/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase;

/**
 *
 * @author jyarango
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtDni = new javax.swing.JTextField();
        jtxtNombres = new javax.swing.JTextField();
        jcbxCargo = new javax.swing.JComboBox<>();
        jcbxArea = new javax.swing.JComboBox<>();
        jbtnMostrarCalculos = new javax.swing.JButton();
        jbtnNuevosCalculos = new javax.swing.JButton();
        jspnAnios = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaResumenPagos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sesion 01 - Clases y Objetos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACIÓN DEL JEFE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtDni.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));
        jPanel1.add(jtxtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, 70));

        jtxtNombres.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRES"));
        jPanel1.add(jtxtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 70));

        jcbxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GERENTE", "SUBGERENTE" }));
        jcbxCargo.setBorder(javax.swing.BorderFactory.createTitledBorder("CARGO"));
        jPanel1.add(jcbxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, 60));

        jcbxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONTABILIDAD", "PLANIFICACION" }));
        jcbxArea.setBorder(javax.swing.BorderFactory.createTitledBorder("AREA"));
        jPanel1.add(jcbxArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 280, 60));

        jbtnMostrarCalculos.setText("MOSTRAR CALCULOS");
        jbtnMostrarCalculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostrarCalculosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMostrarCalculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 250, 50));

        jbtnNuevosCalculos.setText("NUEVOS CALCULOS");
        jbtnNuevosCalculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevosCalculosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNuevosCalculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 250, 50));

        jspnAnios.setBorder(javax.swing.BorderFactory.createTitledBorder("AÑOS ANTIGUEDAD"));
        jPanel1.add(jspnAnios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 280, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 540));

        jtxaResumenPagos.setColumns(20);
        jtxaResumenPagos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxaResumenPagos.setRows(5);
        jtxaResumenPagos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN PAGOS DEL JEFE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jScrollPane1.setViewportView(jtxaResumenPagos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 430, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMostrarCalculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarCalculosActionPerformed
        //lectura de datos de los objetos del formulario para crear un objeto de la clase Jefe
        String nom = this.jtxtNombres.getText(); // getText() -> obtiene el texto de un TextField
        String dn = this.jtxtDni.getText();
        String car = this.jcbxCargo.getSelectedItem().toString(); //getSelectedItem -> obtiene el item seleccionado
        String ar = this.jcbxArea.getSelectedItem().toString();
        int aa = Integer.parseInt(this.jspnAnios.getValue().toString()); //getValue()-> obtiene el valor del Spinner
        //creamos el objeto de la clase jefe
        Jefe je = new Jefe(nom, dn, car, ar, aa);//mostramos los datos de los pagos en el TextArea
        this.jtxaResumenPagos.setText("\nNombres                                 : " + je.nombres 
                                                            + "\nDni                                        : " + je.dni
                                                            + "\nCargo                                    : " + je.cargo
                                                            + "\nArea                                      : " + je.area
                                                            + "\nAños de antiguedad             : " + je.aniosant
                                                            + "\n ************* PAGOS ****************"
                                                            + "\nSueldo base                          : " + je.CalcularSueldoBase()
                                                            + "\nBonificación                          : " + je.CalcularBonificacion()
                                                            + "\nSueldo Final                         : " + je.CalcularSueldoFinal());
    }//GEN-LAST:event_jbtnMostrarCalculosActionPerformed

    private void jbtnNuevosCalculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevosCalculosActionPerformed
        //limpia los objetos para un nuevo ingreso de datos
        this.jtxtNombres.setText(""); // setText("") establece el texto "" sobre el TextField
        this.jtxtDni.setText("");this.jcbxCargo.setSelectedIndex(0);//setSelectedIndex(0) establece el indice seleccion en 0(primer item)
        this.jcbxArea.setSelectedIndex(0);this.jspnAnios.setValue(0); // setValue(0) establece el valor de 0 en el spinner
        this.jtxaResumenPagos.setText("");
        this.jtxtNombres.requestFocus(); // requestFocus() -> coloca el cursor(focus) en el objeto jtxtNombres
    }//GEN-LAST:event_jbtnNuevosCalculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnMostrarCalculos;
    private javax.swing.JButton jbtnNuevosCalculos;
    private javax.swing.JComboBox<String> jcbxArea;
    private javax.swing.JComboBox<String> jcbxCargo;
    private javax.swing.JSpinner jspnAnios;
    private javax.swing.JTextArea jtxaResumenPagos;
    private javax.swing.JTextField jtxtDni;
    private javax.swing.JTextField jtxtNombres;
    // End of variables declaration//GEN-END:variables
}
